# compiled on ubuntu:22.04 (docker)
# apt update && apt install g++ make uuid-dev && make

all:
	g++ -static -O0 --std=c++2b main.cpp -o perune -luuid

# sha256sum perune
# 5fb58eb53a97f866f97218fc053541beeda6b2d09f5b1e450769ea7073a28ce6  perune
