# compiled on ubuntu:22.04 (docker)
# apt update && apt install g++ make uuid-dev && make

all:
	g++ -static -O0 --std=c++2b main.cpp -o perune -luuid

# sha256sum perune
# 9268e815cddecd170e7f39c20b43648710937e1aa55e997f9cec0fc2695613b0  perune
