// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: proto/api.proto

package models

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Werk_Hello_FullMethodName = "/models.Werk/Hello"
)

// WerkClient is the client API for Werk service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WerkClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type werkClient struct {
	cc grpc.ClientConnInterface
}

func NewWerkClient(cc grpc.ClientConnInterface) WerkClient {
	return &werkClient{cc}
}

func (c *werkClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, Werk_Hello_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WerkServer is the server API for Werk service.
// All implementations must embed UnimplementedWerkServer
// for forward compatibility
type WerkServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedWerkServer()
}

// UnimplementedWerkServer must be embedded to have forward compatible implementations.
type UnimplementedWerkServer struct {
}

func (UnimplementedWerkServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedWerkServer) mustEmbedUnimplementedWerkServer() {}

// UnsafeWerkServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WerkServer will
// result in compilation errors.
type UnsafeWerkServer interface {
	mustEmbedUnimplementedWerkServer()
}

func RegisterWerkServer(s grpc.ServiceRegistrar, srv WerkServer) {
	s.RegisterService(&Werk_ServiceDesc, srv)
}

func _Werk_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WerkServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Werk_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WerkServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Werk_ServiceDesc is the grpc.ServiceDesc for Werk service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Werk_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "models.Werk",
	HandlerType: (*WerkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Werk_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/api.proto",
}
