version: '2.2'

services:
  werk:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "always"
    stop_grace_period: 3s
    mem_limit: 1G
    memswap_limit: 1G
    pids_limit: 80
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    ports:
      - "7654:7654"

