ADJECTIVES = [
    'SLOVAN',
    'ŞLOVAN',
    'SLOVАN',
    'SLОVАN',
    'SLОVAN',
    'SLОV4N',
    'GLORY',
    'GLОRY',
    'GLОЯY',
    'ĞLОRY',
    'VELIKIY',
    'VЕLIKIY',
    'VЕLIКIY',
    'VELIКIY',
    'СЛОВЯНСКИЙ',
    'СЛОВЯНСКIЙ',
    'CЛОВЯНСКИЙ',
    'CЛОВЯНСKИЙ',
    'CЛОBЯНСKИЙ',
    'CЛОBRНСKИЙ',
    'CЛОBRНСKIЙ',
    'CЛАBЯНСKIЙ',
    'CЛABЯНСKNЙ',
    'CЛABЯНCKIY',
    'СЛАВЯНСКИЙ',
    'CЛАВЯНСКIY',
    'CЛ4ВЯНСКIY',
    'SLAVANSKIY',
    'SLOVANSKIY',
    'ŞLАVАNSКIY',
    'ВЕЛКИОРУСЫЙ',
    'ВЕЛКIОРУCЫЙ',
    'ВЕЛКИОРУСIY',
    'ВЕЛKИОРУСЫЙ',
    'BЕЛKИОРУСЫЙ',
    'VELIKORUSIY',
    'VЕLIKORUSIY',
    'VЕLIKОRUSIY',
    'VЕLIKОRUŞIY',
    'SLAVIC',
    'SLАVIC',
    'ŞLАVIC',
    'ŞLАВIC',
    'MATUSHKIN',
    'МАTUSHKIN',
    'MOTHERS',
    'МОTHERS',
    'МАТУШКИН',
    'МАТУШКIН',
    'Противоящеровый',
    'ПPОTИВОIAЩЕРOBЫЙ',
    'ПРОTИВОЯAЩЕРOBЫI',
    'ANTILIZZARDS'
    'АNTILIZZАRDS'
    'PROTIVOYASHEROVIY',
    'PROTIVOYASHERОVIY',
    'BAGIROFFS',
    'BAĞIROFFS',
    'BAGIROFFŞ',
    'BАGIROFFS',
    'БОЕВОЙ',
    'BOEVOI',
    'ПЕРУНСКИЙ',
    'PERUN',
    'ЯЗЫЧЕСКИЙ',
    'YAZICHESKY',
    'PAGAN',
    'ГУБИТЕЛЬНЫЙ',
    'GUBITELNIY',
]
ADJECTIVES_WITH_I = list(filter(lambda x: 'I' in x, ADJECTIVES))

ACTIONS = [
    'ЗАЖИМ',
    'ZAGIM',
    'CLAMP',
    'UDAR',
    'УДАР',
    'HIT',
    'ŞTRIKE',
    'STRIKE',
    'KICK',
    'SHOT',
    'BEAT',
    'ОБСТРЕЛ',
    'OBSTREL',
    'FIRE',
    'SHELLING',
    'ПРИШИБ',
    'KNOCK',
    'PRISHIB',
    'ПРОСТРЕЛ',
    'LUMBAGO',
    'PROSTREL',
    'ОГОНЬ',
    'OGONb',
    'ТОЛЧОК',
    'TOLCHOK',
    'PUSH',
    'УДУШЕНИЕ',
    'UDUSHENIE',
    'STRANGULATION',
    'ШЕПТУН',
    'SHEPTUN',
    'WHISPER',
    'БРОСОК',
    'BROSOK',
    'THROWS',
    'ПЛЯС',
    'PLIAS',
    'ARTILLERY',
    'PERDESH',
    'РАСКРУЧИВАНИЕ',
    'RASCRUCHIVANIE',
]
ACTIONS_WITH_I = list(filter(lambda x: 'I' in x, ACTIONS))

ITEMS = [
    '$O$KОМ',
    'СОСКОМ',
    '41ЕН0М',
    'SP3RMOI',
    'HYIem',
    'ЯЙЦАМИ',
    'EGGS',
    'BALLS',
    '$И$СК4МИ',
    '$И$К4МИ',
    'ПИ$К4МИ',
    'БУЛКАМИ',
    'BULKAMI',
    'BACK',
    'ПОРТКАМИ',
    'MOSHONKOI',
    'МО4ОНКОЙ',
    'SCROTUM',
    'Z4LUP0I',
    'ЗАПУП0Й',
    'ZAPUPOI',
    'ВО ИМЯ ПЕРУНА',
    'VO IMA PERUNA',
    'in the name of Perun',
    'GOLOVOI',
    'GOLOVKOI',
    'ГОЛОВЕШКОЙ',
    'ГОЛОВЕЩКОЙ',
    'Г4ПОВК0Й',
    'РАДИУСОМ В 2 КИЛОМЕТРА',
]

ITEMS_WITH_I = list(filter(lambda x: 'I' in x, ITEMS))

NAMES = [
    'Ostromir',
    'Tihomir',
    'Niemir',
    'Vsevolod',
    'Rogvolod',
    'Svetopolk',
    'Yaropolk',
    'Vladislav',
    'Dobroslav',
    'Vseslav',
    'Dobrynya',
    'Tishila',
    'Ratisha',
    'Putyata',
    'Shchuka',
    'Yersh',
    'Zayac',
    'Wolk',
    'Orel',
    'Pervusha',
    'Vtorusha',
    'Vtorak',
    'Tretiusha',
    'Tretiusha',
    'Tretyak',
    'Hrabr',
    'Milena',
    'Milana',
    'Milosh',
    'Perunek',
    'Troyan',
    'Yarovit',
    'Šventaragis',
    'Stribor',
    'Veleslava',
]


available_replacement = [
    {'K': 'К'},
    {'К': 'K'},
    {'И': 'I'},
    {'A': 'А'},
    {'Н': 'H'},
    {'E': 'Е'},
    {'Е': 'E'},
    {'O': 'O'},
    {'O': '0'},
    {'O': 'О'},
    {'А': 'A'},
    {'G': 'Ğ'},
    {'И': 'N'},
    {'N': 'И'},
    {'Я': 'IA'},
    {'В': 'B'},
    {'B': 'В'},
    {'S': '$'},
    {'S': 'Ş'},
    {'З': '3'},
    {'З': 'Z'},
    {'P': 'Р'},
    {'Р': 'P'},
    {'R': 'Я'},
    {'T': 'Т'},
    {'Т': 'T'},
    {'C': 'С'},
    {'С': 'C'},
    {'Ы': 'I'},
    {'Ч': '4'},
    {'Й': 'IY'},
    {'Й': 'I'},
    {'У': 'Y'},
    {'Y': 'У'},
    {'L': '1'},
]

available_replacement_to_i = list(filter(lambda x: 'I' in next(iter(x.values())), available_replacement))