# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nauth.proto\"K\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x14\n\x0cspecies_type\x18\x03 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\" \n\rRegisterReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\"\n\nLoginReply\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t2[\n\x06\x41uther\x12,\n\x08Register\x12\x10.RegisterRequest\x1a\x0e.RegisterReply\x12#\n\x05Login\x12\r.LoginRequest\x1a\x0b.LoginReplyB\x06\xaa\x02\x03\x41PIb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'\252\002\003API'
    _globals['_REGISTERREQUEST']._serialized_start = 14
    _globals['_REGISTERREQUEST']._serialized_end = 89
    _globals['_LOGINREQUEST']._serialized_start = 91
    _globals['_LOGINREQUEST']._serialized_end = 141
    _globals['_REGISTERREPLY']._serialized_start = 143
    _globals['_REGISTERREPLY']._serialized_end = 175
    _globals['_LOGINREPLY']._serialized_start = 177
    _globals['_LOGINREPLY']._serialized_end = 211
    _globals['_AUTHER']._serialized_start = 213
    _globals['_AUTHER']._serialized_end = 304
# @@protoc_insertion_point(module_scope)
