FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update \
    && apt install -y wget xz-utils libjpeg9 libjpeg9-dev libfreetype6 libfreetype-dev libfreetype6-dev fontconfig libfontconfig-dev libfontconfig1 libfontconfig1-dev gcc g++ cmake

WORKDIR /tmp/build

RUN wget https://mirror.surf/imagemagick/ImageMagick-7.1.1-21.tar.xz \
    && tar -xf ImageMagick-7.1.1-21.tar.xz

WORKDIR /tmp/build/ImageMagick-7.1.1-21

RUN ./configure --with-security-policy=websafe --with-freetype=yes --enable-shared=no --enable-static=yes --enable-delegate-build --disable-openmp --without-threads \
    && make -j8 \
    && strip -s utilities/magick

RUN ./utilities/magick --version
