services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.3
    entrypoint: /usr/local/bin/etcd

    command:
      - '--name=etcd-1'
      - '--initial-advertise-peer-urls=http://etcd:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd:2379'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
      - '--initial-cluster=etcd-1=http://etcd:2380'
      - '--initial-cluster-state=new'
      - '--initial-cluster-token=etcd-cluster-token'
    volumes:
      - etcd1:/etcd_data
    ports:
      - 2379:2379
    restart: always

  rustest:
    build: "./"
    ports:
      - 3000:13337
    restart: always

volumes:
  etcd1:
