version: "3.7"

services:
  werk:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:7.2.0-alpine
    restart: unless-stopped
    volumes:
      - "redis-data:/data"
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning

volumes:
  redis-data: {}
