version: '3.0'

services:
  api:
    build: .
    ports:
      - '42424:8000'
    restart: always
    depends_on:
      - postgres
      - redis
  postgres:
    build: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    build: redis
    restart: always
    ports: 
      - '6379:6379'
    volumes:
      - redis-cache:/data
  db_to_redis:
    build: db_to_redis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    restart: always


volumes:
  postgres-data:
  redis-cache:

