name: Check example
on:
  push:
    branches:
      - master
    paths:
      - 'services/example/**'
      - 'checkers/example/**'
      - 'sploits/example/**'
  workflow_dispatch:
    inputs:
      manual_run:
        required: false
jobs:
  check_service_example:
    name: Check service example
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup example
      run: (cd ./services/example && docker-compose pull && docker-compose build && docker-compose up --build -d)
  check_checker_example:
    name: Check checker example
    runs-on: ubuntu-20.04
    if: ${{ true }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup example
      run: (cd ./services/example && docker-compose pull && docker-compose build && docker-compose up --build -d)
    - name: Sleep some time. Wait service ready
      run: sleep 30
    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Setup checker libraries
      run: if [ -f checkers/example/requirements.txt ]; then python -m pip install -r checkers/example/requirements.txt; fi
    - name: Test checker on service
      run: (cd ./checkers/example && ./example.checker.py TEST 127.0.0.1)
  check_sploit_example:
    name: Check sploit example
    runs-on: ubuntu-20.04
    if: ${{ true }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup example
      run: (cd ./services/example && docker-compose pull && docker-compose build && docker-compose up --build -d)
    - name: Sleep some time. Wait service ready
      run: sleep 30
    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Setup checker libraries
      run: if [ -f checkers/example/requirements.txt ]; then python -m pip install -r checkers/example/requirements.txt; fi
    - name: Setup sploit libraries
      run: if [ -f sploits/example/requirements.txt ]; then python -m pip install -r sploits/example/requirements.txt; fi
    - name: Test sploit on service
      run: (./tools/check_sploit.py example)
