name: Check rusi-trainer
on:
  push:
    branches:
      - master
    paths:
      - 'services/rusi-trainer/**'
      - 'checkers/rusi-trainer/**'
      - 'sploits/rusi-trainer/**'
  workflow_dispatch: {}
jobs:
  check_service_rusi-trainer:
    name: Check service rusi-trainer
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup rusi-trainer
      run: (cd ./services/rusi-trainer && docker-compose pull && docker-compose build && docker-compose up --build -d)
  check_checker_rusi-trainer:
    name: Check checker rusi-trainer
    runs-on: ubuntu-20.04
    if: ${{ true }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup rusi-trainer
      run: (cd ./services/rusi-trainer && docker-compose pull && docker-compose build && docker-compose up --build -d)
    - name: Sleep some time. Wait service ready
      run: sleep 30
    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Setup checker libraries
      run: if [ -f checkers/rusi-trainer/requirements.txt ]; then python -m pip install -r checkers/rusi-trainer/requirements.txt; fi
    - name: Test checker on service
      run: (cd ./checkers/rusi-trainer && ./rusi-trainer.checker.py TEST 127.0.0.1)
  check_sploit_rusi-trainer:
    name: Check sploit rusi-trainer
    runs-on: ubuntu-20.04
    if: ${{ true }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup rusi-trainer
      run: (cd ./services/rusi-trainer && docker-compose pull && docker-compose build && docker-compose up --build -d)
    - name: Sleep some time. Wait service ready
      run: sleep 30
    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Setup checker libraries
      run: if [ -f checkers/rusi-trainer/requirements.txt ]; then python -m pip install -r checkers/rusi-trainer/requirements.txt; fi
    - name: Setup sploit libraries
      run: if [ -f sploits/rusi-trainer/requirements.txt ]; then python -m pip install -r sploits/rusi-trainer/requirements.txt; fi
    - name: Test sploit on service
      run: TERM=linux ./tools/check_sploit.py rusi-trainer 127.0.0.1
  check_stand_checker_rusi-trainer:
    name: Check stand checker rusi-trainer
    runs-on: self-hosted
    if: ${{ false }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup checker libraries
      run: if [ -f checkers/rusi-trainer/requirements.txt ]; then python3 -m pip install -r checkers/rusi-trainer/requirements.txt; fi
    - name: Test checker on service
      run: (cd ./checkers/rusi-trainer && ./rusi-trainer.checker.py TEST test1.cloud.ructf.org)
  check_stand_sploit_rusi-trainer:
    name: Check stand sploit rusi-trainer
    runs-on: self-hosted
    if: ${{ false }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup checker libraries
      run: if [ -f checkers/rusi-trainer/requirements.txt ]; then python3 -m pip install -r checkers/rusi-trainer/requirements.txt; fi
    - name: Setup sploit libraries
      run: if [ -f sploits/rusi-trainer/requirements.txt ]; then python3 -m pip install -r sploits/rusi-trainer/requirements.txt; fi
    - name: Test sploit on service
      run: TERM=linux ./tools/check_sploit.py rusi-trainer test1.cloud.ructf.org
