name: Check werk
on:
  push:
    branches:
      - master
    paths:
      - 'services/werk/**'
      - 'checkers/werk/**'
      - 'sploits/werk/**'
  workflow_dispatch: {}
jobs:
  check_service_werk:
    name: Check service werk
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup werk
      run: (cd ./services/werk && docker-compose pull && docker-compose build && docker-compose up --build -d)
  check_checker_werk:
    name: Check checker werk
    runs-on: ubuntu-20.04
    if: ${{ true }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup werk
      run: (cd ./services/werk && docker-compose pull && docker-compose build && docker-compose up --build -d)
    - name: Sleep some time. Wait service ready
      run: sleep 30
    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Setup checker libraries
      run: if [ -f checkers/werk/requirements.txt ]; then python -m pip install -r checkers/werk/requirements.txt; fi
    - name: Test checker on service
      run: (cd ./checkers/werk && ./werk.checker.py TEST 127.0.0.1)
  check_sploit_werk:
    name: Check sploit werk
    runs-on: ubuntu-20.04
    if: ${{ true }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup werk
      run: (cd ./services/werk && docker-compose pull && docker-compose build && docker-compose up --build -d)
    - name: Sleep some time. Wait service ready
      run: sleep 30
    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Setup checker libraries
      run: if [ -f checkers/werk/requirements.txt ]; then python -m pip install -r checkers/werk/requirements.txt; fi
    - name: Setup sploit libraries
      run: if [ -f sploits/werk/requirements.txt ]; then python -m pip install -r sploits/werk/requirements.txt; fi
    - name: Test sploit on service
      run: (./tools/check_sploit.py werk)
