name: Check perune
on:
  push:
    branches:
      - master
    paths:
      - 'services/perune/**'
      - 'checkers/perune/**'
      - 'sploits/perune/**'
  workflow_dispatch: {}
jobs:
  check_service_perune:
    name: Check service perune
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup perune
      run: (cd ./services/perune && docker-compose pull && docker-compose build && docker-compose up --build -d)
  check_checker_perune:
    name: Check checker perune
    runs-on: ubuntu-20.04
    if: ${{ true }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup perune
      run: (cd ./services/perune && docker-compose pull && docker-compose build && docker-compose up --build -d)
    - name: Sleep some time. Wait service ready
      run: sleep 30
    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Setup checker libraries
      run: if [ -f checkers/perune/requirements.txt ]; then python -m pip install -r checkers/perune/requirements.txt; fi
    - name: Test checker on service
      run: (cd ./checkers/perune && ./perune.checker.py TEST 127.0.0.1)
  check_sploit_perune:
    name: Check sploit perune
    runs-on: ubuntu-20.04
    if: ${{ true }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup perune
      run: (cd ./services/perune && docker-compose pull && docker-compose build && docker-compose up --build -d)
    - name: Sleep some time. Wait service ready
      run: sleep 30
    - name: Prepare python for checker
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Setup checker libraries
      run: if [ -f checkers/perune/requirements.txt ]; then python -m pip install -r checkers/perune/requirements.txt; fi
    - name: Setup sploit libraries
      run: if [ -f sploits/perune/requirements.txt ]; then python -m pip install -r sploits/perune/requirements.txt; fi
    - name: Test sploit on service
      run: (./tools/check_sploit.py perune 127.0.0.1)
  check_stand_sploit_perune:
    name: Check stand sploit perune
    runs-on: self-hosted
    if: ${{ true }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup checker libraries
      run: if [ -f checkers/perune/requirements.txt ]; then python3 -m pip install -r checkers/perune/requirements.txt; fi
    - name: Setup sploit libraries
      run: if [ -f sploits/perune/requirements.txt ]; then python3 -m pip install -r sploits/perune/requirements.txt; fi
    - name: Test sploit on service
      run: TERM=linux ./tools/check_sploit.py perune test1.cloud.ructf.org
